# Generated by Django 6.0.3 on 2026-03-14 11:44

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading_block", 2),
                            ("paragraph_block", 3),
                            ("image_block", 6),
                            ("embed_block", 7),
                            ("card", 10),
                            ("featured_posts", 14),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"form_classname": "title", "required": True},
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "blank": True,
                                    "choices": [
                                        ("", "Select a heading size"),
                                        ("h2", "H2"),
                                        ("h3", "H3"),
                                        ("h4", "H4"),
                                    ],
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("heading_text", 0), ("size", 1)]],
                                {},
                            ),
                            3: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"icon": "pilcrow"},
                            ),
                            4: ("wagtail.images.blocks.ImageBlock", [], {}),
                            5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 4), ("caption", 5), ("attribution", 5)]],
                                {},
                            ),
                            7: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {
                                    "help_text": "Insert a URL to embed. For example, https://www.youtube.com/watch?v=SGJFWirQ3ks",
                                    "icon": "media",
                                },
                            ),
                            8: ("wagtail.blocks.CharBlock", (), {}),
                            9: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link"]},
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 8), ("text", 9), ("image", 4)]],
                                {"group": "Sections"},
                            ),
                            11: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "required": False,
                                },
                            ),
                            12: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"page_type": ["blog.BlogPage"]},
                            ),
                            13: ("wagtail.blocks.ListBlock", (12,), {}),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 8), ("text", 11), ("posts", 13)]],
                                {"group": "Sections"},
                            ),
                        },
                        help_text="Use this section to list your projects and skills.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
